script:
  - docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:bionic /bin/bash travis-build.sh

branches:
  only:
  - master
  - development

deploy:
- provider: script
  script: ./source/nitrux-repository-util.sh *.deb
  skip_cleanup: true

notifications:
  email: false
